# Generated by Django 5.1.4 on 2025-01-08 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_beneficiary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('acronyme', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='name',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_accounts', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='beneficiary_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_of', to=settings.AUTH_USER_MODEL, verbose_name='Bénéficiaire'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='banque',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='accounts.banque'),
        ),
    ]
