# Generated by Django 5.1.4 on 2025-01-08 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_banque_remove_beneficiary_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='numero_compte',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='banque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='accounts.banque'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_accounts', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='beneficiary_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
